name: asor
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.23  # Compatible con numba y otras dependencias
  - pandas=1.5
  - polars=0.18
  - scipy=1.9
  - matplotlib=3.6
  - seaborn=0.12
  - scikit-learn=1.2
  - statsmodels=0.13
  - nltk=3.8
  - xgboost=1.7
  - lightgbm=3.3
  - catboost=1.2
  - imbalanced-learn=0.10
  - tpot=0.11
  - optuna=3.0
  - h2o=3.36
  - tensorflow=2.10
  - keras=2.10
  - pytorch=1.13
  - fastai=2.7
  - transformers=4.24
  - tensorflow-hub=0.12
  - opencv=4.6
  - plotly=5.10
  - bokeh=3.0
  - altair=4.2
  - folium=0.14
  - geopandas=0.12
  - pyproj=3.4
  - mlflow=2.1
  - dvc=2.38
  - kubeflow-katib=0.12
  - tensorboard=2.10
  - seldon-core=1.15
  - pytesseract=0.3
  - pathlib=1.0
  - glob2=0.7
  - django=4.1
  - flask=2.2
  - arch=7.2.0
  - pip
  - missingno=0.5.2
  - upsetplot=0.9.0
  - openpyxl==3.1.0
  - pip:
      - seldon-core
      - kubeflow-training
